In [1]:
# Load Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['Sepal-length', 'Sepal-width', 'Petal-length', 'Petal-width', 'Class']
iris = pd.read_csv(url, names = names) 

In [4]:
iris.head()

Sepal-length  Sepal-width  Petal-length  Petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
x = pd.DataFrame(iris[['Sepal-length', 'Sepal-width', 'Petal-length', 'Petal-width']])
y = iris['Class']

In [7]:
# Splitting into train and test

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [8]:
# Building the model

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [9]:
# Predicting the values

y_pred = classifier.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[15  0  0]
 [ 0 16  0]
 [ 0  0 14]]


The confusion matrix indicates that THE LEFT DIAGONAL VALUES THAT ARE CORRECTLY PREDICTED AND THE REST OF THE VALUES ARE MISCALCULATED:

There are 15 samples that belong to class 0 (the first row) and all of them were correctly classified as class 0 (the first column).
There are 16 samples that belong to class 1 (the second row) and all of them were correctly classified as class 1 (the second column).
There are 14 samples that belong to class 2 (the third row) and all of them were correctly classified as class 2 (the third column).
Therefore, the model achieved perfect accuracy on the test data, as all samples were classified correctly.

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

1.0


In this case, the output 1.0 indicates that the model achieved perfect accuracy on the test data, meaning that it correctly predicted all the samples in the test set. This is a very good result, and it suggests that the model is likely to be performing well on similar data. However, it is important to note that achieving perfect accuracy on a single test set does not necessarily mean that the model is the best or most appropriate model for the given problem. It is always important to evaluate a model's performance on multiple test sets and to consider other factors such as interpretability and scalability before making a final decision.